### ISSUE TITLE
To-Do: Datenbank Modelle

### ISSUE THREAD

**Issue by mimischi** [GeoMatDigital/django-geomat#7]
Beim letzten Meeting wurden einige Punkte angesprochen, welche wir aktuell noch nicht abgearbeitet haben.

- [x] Die Felder [Mohs Härte und Dichte](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L101-L107) sind aktuell CharFields. Gewünscht wären hier allerdings [FloatRangeFields](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#floatrangefield). Optimalerweise sollten diese auch innerhalb eines neuen ArrayFields realisiert werden, damit diese Felder mehrere Ranges pro Mineralart speichern können.

- [x] Das [Kommentarfeld](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L179-L183) ist aktuell ein CharField und soll zu einem TextField umgewandelt werden
- [x] Für das Feld [Chemismus](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L175-L178) wäre eine Art WYSIWYG-Editor oder zumindest eine Live-Vorschau der LaTeX Syntax mit Hilfe von MathJax (o. ä.) wünschenswert.
- [x] Die [deutsche Übersetzung](https://github.com/GeoMatDigital/django-geomat/blob/master/locale/de/LC_MESSAGES/django.po#L110-L112) von 'Splintery' hat einen Tippfehler (aktuell: 'Splitterig', soll: 'Splittrig').
- [x] [Strichfarbe und Normalfarbe](https://github.com/GeoMatDigital/django-geomat/blob/master/geomat/stein/models.py#L108=L114) bräuchten Optimalerweise auch eine Auswahl aus Farbmöglichkeiten, damit das in Zukunft sortierbar ist. Aktuell ist beides jeweils mit einem CharField realisiert.

**Comment by chgad** [comment]
@ Kommentarfeld : ist zu finden unter Mineralhinzufügen und dort das Feld "Weiters"
@ Deutsche Übersetzung : ist erledigt .
